import type { Metadata } from "next";


import '../assets/Styles/Login/Login.css'
import '../assets/Styles/Home/Home.css'




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


    <body

    >
    {children}
    </body>
    </html>
  );
}
